### ISSUE TITLE
Question about converting shader to a LUT

### ISSUE THREAD

**Issue by Bananaman** [CeeJayDK/SweetFX#4]
Hi CeeJay, awesome work on your shaders!

I am unable to understand the math of the Technicolor 2 shader:

https://github.com/CeeJayDK/SweetFX/blob/master/Shaders/Technicolor2.fx

Is that math dynamic based on the image? Or is it safe/possible to convert that whole effect to a static LUT (with zero visual differences)?

**Comment by CeeJayDK** [comment]
It's possible to convert one set of settings to a LUT with only minor differences (because of the limited resolution of most LUTs) but as soon as you modify the settings you would need another LUT.

You could however apply the strength setting to the LUT as well and get the same result as the strength setting in the original.

Converting it to a LUT however does not make sense since you use LUTs to save making the calculations, but with this simple shader you don't really save any performance I should think.
